version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - flaq_net

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - flaq_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    logging:
      driver: none
    networks:
      - flaq_net

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - flaq_net

  workers:
    container_name: "flaq-workers"
    build:
      context: ./workers
    environment:
      AMQP_SERVER_URL: amqp://rabbitmq:5672
      RPC_URL: ${RPC_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      PRIVATE_KEY: ${PRIVATE_KEY}
    restart: always
    networks:
      - flaq_net
    depends_on:
      - rabbitmq
      - cache
      - api

  api:
    container_name: "flaq-api"
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    environment:
      AMQP_SERVER_URL: amqp://rabbitmq:5672
      PG_HOST: db
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_PORT: 5432
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    networks:
      - flaq_net
    depends_on:
      - rabbitmq
      - db

  scheduler:
    container_name: "scheduler"
    build:
      context: ./scheduler
    environment:
      AMQP_SERVER_URL: amqp://rabbitmq:5672
      REDIS_URL: "cache:6379"
    restart: always
    networks:
      - flaq_net
    depends_on:
      - rabbitmq
      - cache
      - api

networks:
  flaq_net:
    driver: bridge
# vpc-0ddb1d66
#
#  subnet-5f816e34
# |  subnet-f8781f83
# |  subnet-c4aaf788
#
