version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - flaq_net
  mailer:
    container_name: "flaq-mailer"
    build:
      context: ./mailer
    environment:
      AMQP_SERVER_URL: amqp://rabbitmq:5672
    restart: always
    networks:
      - flaq_net
    depends_on:
      - rabbitmq
      - api

  api:
    container_name: "flaq-api"
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    environment:
      AMQP_SERVER_URL: amqp://rabbitmq:5672
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    networks:
      - flaq_net
    depends_on:
      - rabbitmq

networks:
  flaq_net:
    driver: bridge
# vpc-0ddb1d66
#
#  subnet-5f816e34
# |  subnet-f8781f83
# |  subnet-c4aaf788
#
