version: "3.8"

services:
  # db:
  #   image: postgres:15.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - flaq_net

  workers:
    container_name: "flaq-workers"
    build:
      context: ./workers
    environment:
      AMQP_SERVER_URL: amqp://host.docker.internal:5672
      ETH_RPC_URL: ${ETH_RPC_URL}
      CONTRACT_ADDRESS_QUIZ: ${CONTRACT_ADDRESS_QUIZ}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      PRIVATE_KEY: ${PRIVATE_KEY}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      PG_HOST: db
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_PORT: 5432
      AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      CHROME_DP_URL: "http://host.docker.internal:9222"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: always
    networks:
      - default
    env_file:
      - .dev.env
    depends_on:
      - api

  api:
    container_name: "flaq-api"
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    environment:
      AMQP_SERVER_URL: amqp://host.docker.internal:5672
      PG_HOST: db
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_PORT: 5432
      POAP_MINT_SECRET: testmint
      SCRAPER_TOKEN: ${SCRAPER_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GAUTH_CLIENT_KEY: ${GAUTH_CLIENT_KEY}
      GAUTH_SECRET: ${GAUTH_SECRET}
      GAUTH_CALLBACK_URL: ${GAUTH_CALLBACK_URL}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    networks:
      - default

  scheduler:
    container_name: "scheduler"
    build:
      context: ./scheduler
    environment:
      AMQP_SERVER_URL: amqp://host.docker.internal:5672
      REDIS_URL: "host.docker.internal:6379"
    restart: always
    networks:
      - default
    depends_on:
      - api

networks:
  default:
    name: flaq_net
    external: true
    # driver: bridge
# vpc-0ddb1d66
#
#  subnet-5f816e34
# |  subnet-f8781f83
# |  subnet-c4aaf788
#
