version: "3.8"

services:
  mailer:
    container_name: "flaq-mailer"
    image: 312136753954.dkr.ecr.ap-south-1.amazonaws.com/flaq-mailer
    build:
      context: ./mailer
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
    restart: always
    networks:
      - flaq_net

  api:
    container_name: "flaq-api"
    image: 312136753954.dkr.ecr.ap-south-1.amazonaws.com/flaq-api
    build:
      context: ./api
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      PG_HOST: ${PG_HOST}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: flaqloggroup
    ports:
      - 3000:3000
    networks:
      - flaq_net

networks:
  flaq_net:
    driver: bridge

x-aws-cloudformation:
  Resources:
    WebappTCP443Listener:
      Type: "AWS::ElasticLoadBalancingV2::Listener"
      Properties:
        LoadBalancerArn:
          Ref: LoadBalancer
        DefaultActions:
          - ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: ApiTCP3000TargetGroup
            Type: forward
        Certificates:
          - CertificateArn: "arn:aws:acm:ap-south-1:312136753954:certificate/f5763aa6-5c97-4b40-9b7b-2aa01e7ac0a1"
        Protocol: TLS
        Port: 443
# vpc-0ddb1d66
#
#  subnet-5f816e34
# |  subnet-f8781f83
# |  subnet-c4aaf788
#
